---
strict: true
site_name: p360-contact-manager
site_description: Public 360 contact manager. Removes duplicates, Enrich Enterprise.
theme:
  name: material
  palette:
    primary: green
    accent: deep-orange
  icon:
    logo: material/language-python
  language: en
  features:
    - tabs
repo_name: greenbird/p360-contact-manager
repo_url: https://github.com/greenbird/p360-contact-manager
edit_uri: ""
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home:
      - Home: index.md
      - Usage: usage.md
      - Configuring: configuring.md
      - List of Arguments: arguments.md
      - FAQ: faq.md
  - Contribution:
      - Contribution: contrib/contributing.md
